blank_issues_enabled: true
contact_links:
  - name: Questions & Discussion
    url: https://github.com/dexterity-systems/prefect-submitit/discussions
    about:
      Ask questions and discuss ideas (please don't open issues for support
      questions)
